### ISSUE TITLE
Generate table with date patterns statistics

### ISSUE THREAD

**Issue by niltonvasques** [Marinofull/analysis-password-leak#7]
![screenshot from 2015-11-17 18 06 04](https://cloud.githubusercontent.com/assets/2291529/11224889/fea825a0-8d55-11e5-8248-810e16c6a85a.png)

**Comment by niltonvasques** [comment]
![screenshot from 2015-11-17 18 07 39](https://cloud.githubusercontent.com/assets/2291529/11224920/1ef60750-8d56-11e5-8807-f8b321aba21e.png)

**Comment by Marinofull** [comment]
@niltonvasques veja como botei meu it closes aki, e vai funcionar
